name = "share"
type = "webpack"
workers_dev = true
account_id = "1df4d5d08f27bd020035ab097fea935e"
zone_id = "e033a617a98e3163f10f8c1147ee5fc7"
kv_namespaces = [
    { binding = "BUCKET", id = "e9250910f186447192906796a7527d88" }
]

[env.staging]
name = "share-staging"
